name: test standalone

on:
  workflow_dispatch:

jobs:


  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: test standalone against ${{ matrix.os }}
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.89/pact-1.88.89-win32.zip
          unzip pact-1.88.89-win32.zip
          cd pact
          ./bin/pact-mock-service --help start
          ./bin/pact-provider-verifier --help verify
